import "./globals.css";
import "@/styles/layout-comp.scss";
import "@/styles/button-component.scss";
import "@/styles/inputbox-component.scss";

import { Play } from "next/font/google";

const playFont = Play({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "DSEdify",
  description: "Generated by create next app",

  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={playFont.className}>
      <body>{children}</body>
    </html>
  );
}
